[bumpversion]
current_version = "0.1.1"
commit = true
tag = true
tag_name = "{new_version}"

[[file]]
filename = "./__version__.py"
search = '__version__ = "{current_version}"'
replace = '__version__ = "{new_version}"'
